#!/usr/bin/env bash
# Общие функции для локального запуска Experts Tourister.

local_common_root() {
  if [[ -n "${LOCAL_ROOT:-}" ]]; then
    printf '%s' "$LOCAL_ROOT"
    return
  fi
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "$script_dir/../.." && pwd
}

local_load_env() {
  local root="$1"
  if [[ -f "$root/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "$root/.env"
    set +a
  elif [[ -f "$root/.env.example" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "$root/.env.example"
    set +a
  fi
  if [[ -f "$root/.local/ports.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "$root/.local/ports.env"
    set +a
  fi
}

# OrbStack / Docker Desktop on macOS often bind :8080 and :8081.
local_port_busy() {
  lsof -ti tcp:"$1" -sTCP:LISTEN >/dev/null 2>&1
}

local_is_our_backend_on_port() {
  local port="$1"
  local pids pid cmd
  pids="$(lsof -ti tcp:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  [[ -n "$pids" ]] || return 1
  for pid in $pids; do
    cmd="$(local_pid_cmdline "$pid")"
    local_is_backend_process "$cmd" && return 0
  done
  return 1
}

local_is_our_frontend_on_port() {
  local port="$1"
  local pids pid cmd
  pids="$(lsof -ti tcp:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  [[ -n "$pids" ]] || return 1
  for pid in $pids; do
    cmd="$(local_pid_cmdline "$pid")"
    local_is_frontend_process "$cmd" && return 0
  done
  return 1
}

local_pick_free_port() {
  local port
  for port in "$@"; do
    if ! local_port_busy "$port"; then
      echo "$port"
      return 0
    fi
  done
  echo "✗ no free port among: $*" >&2
  return 1
}

local_resolve_ports() {
  local root="$1"
  local backend_preferred frontend_preferred picked

  BACKEND_PORT="${BACKEND_PORT:-}"
  if [[ -z "$BACKEND_PORT" && -n "${HTTP_ADDR:-}" ]]; then
    BACKEND_PORT="${HTTP_ADDR#:}"
  fi
  BACKEND_PORT="${BACKEND_PORT:-8091}"
  FRONTEND_PORT="${FRONTEND_PORT:-5173}"
  PG_PORT="${PG_PORT:-5433}"
  REDIS_PORT="${REDIS_PORT:-6380}"

  backend_preferred="$BACKEND_PORT"
  if local_port_busy "$backend_preferred" && ! local_is_our_backend_on_port "$backend_preferred"; then
    picked="$(local_pick_free_port 8091 8092 8093 8094 18091 18092)" || exit 1
    echo "→ backend :${backend_preferred} busy (OrbStack?), using :${picked}" >&2
    BACKEND_PORT="$picked"
  fi

  frontend_preferred="$FRONTEND_PORT"
  if local_port_busy "$frontend_preferred" && ! local_is_our_frontend_on_port "$frontend_preferred"; then
    picked="$(local_pick_free_port 5173 5174 5175 5176 4173 4174)" || exit 1
    echo "→ frontend :${frontend_preferred} busy, using :${picked}" >&2
    FRONTEND_PORT="$picked"
  fi

  CORS_ORIGINS="${CORS_ORIGINS:-http://localhost:${FRONTEND_PORT}}"
  PUBLIC_BASE_URL="${PUBLIC_BASE_URL:-http://localhost:${FRONTEND_PORT}}"

  export HTTP_ADDR=":${BACKEND_PORT}"
  export BACKEND_PORT FRONTEND_PORT PG_PORT REDIS_PORT CORS_ORIGINS PUBLIC_BASE_URL

  mkdir -p "$root/.local"
  cat >"$root/.local/ports.env" <<EOF
# Auto-generated by run-local.sh — OrbStack-safe local ports
HTTP_ADDR=:${BACKEND_PORT}
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
CORS_ORIGINS=${CORS_ORIGINS}
PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
PG_PORT=${PG_PORT}
REDIS_PORT=${REDIS_PORT}
EOF
}

local_ensure_dirs() {
  local root="$1"
  mkdir -p "$root/.local/logs" "$root/.local/pids"
}

local_pid_cmdline() {
  local pid="$1"
  ps -p "$pid" -o command= 2>/dev/null | sed 's/^[[:space:]]*//' || true
}

local_is_backend_process() {
  local cmd="$1"
  [[ "$cmd" == *"cmd/api"* ]] \
    || [[ "$cmd" == *"experts-tourister"* ]] \
    || [[ "$cmd" == *"goproject/backend"* ]] \
    || [[ "$cmd" == *"/backend"* && ( "$cmd" == *"go run"* || "$cmd" == *"go-build"* ) ]]
}

local_is_frontend_process() {
  local cmd="$1"
  [[ "$cmd" == *"vite"* ]] && [[ "$cmd" == *"frontend"* || "$cmd" == *"goproject"* || "$cmd" == *"experts-tourister"* ]]
}

# Kill only processes owned by this project. Never kill foreign listeners (e.g. OrbStack on :8081).
local_kill_port() {
  local port="$1"
  local kind="${2:-any}"
  local pids
  pids="$(lsof -ti tcp:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  if [[ -z "$pids" ]]; then
    return 0
  fi

  local pid cmd matched=0
  for pid in $pids; do
    cmd="$(local_pid_cmdline "$pid")"
    [[ -n "$cmd" ]] || continue

    case "$kind" in
      backend)
        local_is_backend_process "$cmd" || continue
        ;;
      frontend)
        local_is_frontend_process "$cmd" || continue
        ;;
      *)
        local_is_backend_process "$cmd" || local_is_frontend_process "$cmd" || continue
        ;;
    esac

    matched=1
    echo "→ stop :$port (pid $pid)"
    kill "$pid" 2>/dev/null || true
  done

  if [[ "$matched" == "1" ]]; then
    sleep 0.5
    for pid in $pids; do
      cmd="$(local_pid_cmdline "$pid")"
      [[ -n "$cmd" ]] || continue
      case "$kind" in
        backend) local_is_backend_process "$cmd" || continue ;;
        frontend) local_is_frontend_process "$cmd" || continue ;;
        *) local_is_backend_process "$cmd" || local_is_frontend_process "$cmd" || continue ;;
      esac
      kill -0 "$pid" 2>/dev/null && kill -9 "$pid" 2>/dev/null || true
    done
    return 0
  fi

  local foreign
  foreign="$(local_pid_cmdline "${pids%% *}")"
  echo "→ skip :$port (occupied by another app: ${foreign:0:72})" >&2
}

local_stop_pidfile() {
  local pidfile="$1"
  local name="$2"
  if [[ -f "$pidfile" ]]; then
    local pid
    pid="$(cat "$pidfile" 2>/dev/null || true)"
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      echo "→ stop $name (pid $pid)"
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
    fi
    rm -f "$pidfile"
  fi
}

local_wait_tcp() {
  local host="$1"
  local port="$2"
  local label="$3"
  local tries="${4:-60}"
  echo "→ wait $label ($host:$port)"
  local i
  for ((i = 1; i <= tries; i++)); do
    if (echo >/dev/tcp/"$host"/"$port") >/dev/null 2>&1; then
      echo "✓ $label ready"
      return 0
    fi
    sleep 1
  done
  echo "✗ timeout waiting for $label ($host:$port)" >&2
  return 1
}

local_print_urls() {
  local backend_port="$1"
  local frontend_port="$2"
  local pg_port="${PG_PORT:-5433}"
  local redis_port="${REDIS_PORT:-6380}"
  echo ""
  echo "══════════════════════════════════════════════"
  echo " Experts Tourister — local"
  echo "──────────────────────────────────────────────"
  echo " API:       http://localhost:${backend_port}"
  echo " Health:    http://localhost:${backend_port}/healthz"
  echo " Frontend:  http://localhost:${frontend_port}"
  echo " Postgres:  localhost:${pg_port}"
  echo " Redis:     localhost:${redis_port}"
  echo "──────────────────────────────────────────────"
  echo " Demo: guide1 / guide12345"
  echo "══════════════════════════════════════════════"
  echo ""
}
